#!/bin/bash

# gulixo bspwm
# github:https://github.com/gulixo/gulixo-dotfiles

# workspaces
bspc monitor -d    

# bspwm config
bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# window rules
bspc rule -a firefox desktop='^2'

# colors
bspc config normal_border_color "#1f1f1f"
bspc config focused_border_color "#ffffff"

# autostart
sxhkd &
~/.config/polybar/launch.sh &
feh --bg-scale ~/Imagens/Wallpapers/wall1.png
